In [1]:
import numpy as np
arr=np.arange(0,10,2)# create array from o to 10 with step 2
arr

array([0, 2, 4, 6, 8])

In [2]:
array=np.linspace(0,10,5)# create array from 0 to 10 with 5 elements
array

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [3]:
b=np.array([0, 2, 4, 6, 8])
b.reshape(5,1)
b.dtype
b.astype(np.float64)
b.dtype

dtype('int64')

In [4]:
Multi_Dimensional_array=np.array([[1,2,3],[4,5,6]])
Multi_Dimensional_array
Multi_Dimensional_array.shape
#Multi_Dimensional_array.ndim
# call ravel() on the array (or call reshape with shape then ravel)
nj=Multi_Dimensional_array.ravel()


In [5]:
array1=np.zeros([4,4])# create 4x4 array with all elements as zero
array1
array1.dtype
#array1.ndim

dtype('float64')

In [8]:
array1=np.array([[1,2,3],
                [4,5,6]])
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
ravel=array1.ravel()
ravel

array([1, 2, 3, 4, 5, 6])

In [22]:
import numpy as np
array=np.array([[1,2,3],
                [4,5,6]])
array
ravel_1=array.ravel()
flatten=array.flatten()
ravel_1[0]=99
print(ravel_1)
print(flatten)


[99  2  3  4  5  6]
[1 2 3 4 5 6]
